imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingerscrossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
    
framework:
    profiler: { only_exceptions: false }

twig:
    debug: true