imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

#doctrine_odm.mongodb:
#    default_database: funsational_development_dev
#    connections:
#        default:
#            options:
#                connect: true
#                persist: funsational_development_dev

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
                              
web_profiler:
    toolbar: true
    intercept_redirects: true

zend:
    logger:
        priority: debug
        path:     %kernel.logs_dir%/%kernel.environment%.log
