framework:
    charset:       UTF-8
    error_handler: nul
    csrf_protection:
        enabled: true
        secret: xxxxxxxxxx
    translator: { fallback: en }
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        # storage_id: funsational_single_domain
        storage_id: pdo
        db_table: sessions
        db_id_col: id
        db_data_col: data
        db_time_col: last_updated
        default_locale: en
        name: pgaz
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
                    
# simple_blog:    
    # db_driver: odm
security:
    providers:
        # fos_userbundle:
            # id: fos_user.user_manager
        main:
            users:
                foo: { password: testing, roles: ROLE_USER }
                admin: {password: admin, roles: ROLE_ADMIN }
        
    factories:
        FunsationalCASFactory: %kernel.root_dir%/../src/Funsational/CASBundle/Resources/config/security_factories.xml
    firewalls:
        profiler:
            pattern: /_profiler/.*
        profiler:
            pattern: /_wdt/.*
        main:
            pattern: /.*
            cas:
                default_domain: development2.funsational.com
            form_login:
                use_forward: false
                provider: main
                use_forward: false
            logout: true
    acl:
        connection: default
    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    
          
# fos_user:
#     db_driver: mongodb
#     provider_key: fos_userbundle
#     class:
#        model:
#            user: Funsational\CommonBundle\Document\User
#            group: FOS\UserBundle\Document\Group
#     

## Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                dbname:   funsational_%kernel.environment%
                user:     root
                password: root
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_generate_proxy_classes: true
        proxy_namespace: Proxies
        proxy_dir: %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager: default
        entity_managers:
            default: 
                mappings:
                    SonataBluePrintBundle: ~
                    #FunsationalCommonBundle: ~
                    # SimpleBlogBundle: ~
                    #SonataNewsBundle: ~
                    #NewsBundle: ~

doctrine_mongo_db:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    default_database: funsational_%kernel.environment%
    document_managers:
        default:
            mappings:
                # SimpleBlogBundle: ~
                # FunsationalCommonBundle: ~
                # FOSUserBundle: ~
    connections:
        default:
                       
## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
