imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
           
web_profiler:
    toolbar: true
    intercept_redirects: true

zend:
    logger:
        priority: debug
        path:     %kernel.logs_dir%/%kernel.environment%.log
