_security_login:
    pattern: /login
    defaults: { _controller: SecurityBundle:Security:login }

_security_check:
    pattern: /login_check

# blog:
#    resource: @SimpleBlogBundle/Resources/config/routing.xml

fos_user_security:
   resource: @FOSUserBundle/Resources/config/routing/security.xml

fos_user_user:
   resource: @FOSUserBundle/Resources/config/routing/user.xml
   prefix: /user


# admin:
#     resource: @SonataAdminBundle/Resources/config/routing/sonata_admin.xml
#     prefix: /admin
# 
# _sonata_base_appliation:
#     resource: .
#     type: sonata_admin

    

