_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemo:Welcome:index }

_demo_secured:
    resource: "@AcmeDemo/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemo/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_security_login:
    pattern: ^/login
    defaults: { _controller: Security:Security:login }

_security_check:
    pattern: ^/login_check

# idea:
    # resource: FunsationalIdeaBundle/Resources/config/routing.xml

# blog:
#    resource: @SimpleBlogBundle/Resources/config/routing.xml
# 
# fos_user_security:
#    resource: @FOSUserBundle/Resources/config/routing/security.xml
# 
# fos_user_user:
#    resource: @FOSUserBundle/Resources/config/routing/user.xml
#    prefix: /user


# admin:
#     resource: @SonataAdminBundle/Resources/config/routing/sonata_admin.xml
#     prefix: /admin
# 
# _sonata_base_appliation:
#     resource: .
#     type: sonata_admin

    

